/* Uke Studio — fichier extrait mécaniquement du bundle validé. Ne pas renommer les fonctions minifiées. */
function Hf(){let[t,e]=(0,E.useState)("home"),[n,a]=(0,E.useState)(0),[l,i]=(0,E.useState)("dark"),[o,s]=(0,E.useState)([]),[m,d]=(0,E.useState)(null),[p,v]=(0,E.useState)(null),[b,x]=(0,E.useState)("");(0,E.useEffect)(()=>{(async()=>{try{let _=await window.storage.get("uke:activepat");_&&d(JSON.parse(_.value))}catch{}})()},[]);let S=async _=>{d(_);try{_?await window.storage.set("uke:activepat",JSON.stringify(_)):await window.storage.delete("uke:activepat")}catch{}};(0,E.useEffect)(()=>{(async()=>{try{let _=await fetch("extra-songs.json",{cache:"no-store"});if(_.ok){let B=await _.json();Array.isArray(B)&&s(B.map(Q=>({...Q,strum:Ut[Q.strumStyle]||Ut.pop})))}}catch{}})()},[]);let[z,y]=(0,E.useState)(null),[c,u]=(0,E.useState)(null),[f,g]=(0,E.useState)([]),[R,C]=(0,E.useState)([]);(0,E.useEffect)(()=>{(async()=>{try{let _=await window.storage.get("uke:favs");_&&C(JSON.parse(_.value))}catch{}try{let _=await ee.get("__cfg-imports");if(_&&_.j)g(JSON.parse(_.j));else{let B=await window.storage.get("uke:imports");B&&g(JSON.parse(B.value))}}catch{}try{let _=await window.storage.get("uke:memlvl");_&&a(parseInt(_.value)||0)}catch{}try{let _=await window.storage.get("uke:theme");_&&i(_.value)}catch{}})()},[]);let T=async _=>{let B=R.includes(_)?R.filter(Q=>Q!==_):[...R,_];C(B);try{await window.storage.set("uke:favs",JSON.stringify(B))}catch{}},A=async _=>{try{let Q=H=>String(H||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();if(f.find(H=>Q(H.title)===Q(_.title)&&Q(_.title).length>2)&&!window.confirm("\u26A0\uFE0F \xAB "+_.title+` \xBB est d\xE9j\xE0 dans ta biblioth\xE8que.
Importer quand m\xEAme en double ?`))return}catch{}let B=[...f,_];g(B),Tf(B)},X=async _=>{let B=f.filter(Q=>Q.id!==_);g(B),Tf(B)},w=async(_,B)=>{let Q=f.map(K=>K.id===_?{...K,...B}:K);g(Q),Tf(Q)};return(0,r.jsxs)("div",{className:"uke","data-theme":l,style:{minHeight:"100vh",background:"var(--bg0)",color:"var(--text)",fontFamily:"'Space Grotesk','Segoe UI',sans-serif"},children:[(0,r.jsx)("style",{children:`
        .uke{ --bg0:#0e1220; --bg1:#10141f; --c1:#131829; --c2:#171d30; --c3:#151b2c; --line:#1e2536; --bd1:#222b42; --bd2:#2a3350;
              --g1:#1c2336; --g2:#161c2c; --str:#39415a; --mut:#3a4360; --faint:#525c74; --tmut:#8a93a8; --tsoft:#aab4cc; --text:#e8ecf4;
              --badge:#151b2cee; --badge2:#151b2caa; --ovl:rgba(8,10,18,.85); --tint1:rgba(255,255,255,0.02); --tint2:rgba(255,255,255,0.025);
              --ball:#ffffff; --ballGlow:rgba(255,255,255,.8); }
        @keyframes pulse { 0%,100%{ opacity:1 } 50%{ opacity:.55 } }
        .uke[data-theme="light"]{ --bg0:#f6f4ee; --bg1:#efece4; --c1:#ffffff; --c2:#f1eee6; --c3:#f6f4ee; --line:#e3dfd4; --bd1:#dcd6c9; --bd2:#c9c2b2;
              --g1:#e7e3d8; --g2:#edeade; --str:#b3ac9b; --mut:#b6b0a0; --faint:#8b8574; --tmut:#6d6a5f; --tsoft:#45423a; --text:#232019;
              --badge:#ffffffee; --badge2:#ffffffcc; --ovl:rgba(244,242,235,.90); --tint1:rgba(0,0,0,0.03); --tint2:rgba(0,0,0,0.035);
              --ball:#232019; --ballGlow:rgba(35,32,25,.55); }
        @import url('https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,600;9..144,700&family=Space+Grotesk:wght@400;500;700&display=swap');
        @keyframes pulse { 0%{transform:scale(1)} 50%{transform:scale(1.1)} 100%{transform:scale(1)} }
        @keyframes pop { 0%{transform:scale(.6);opacity:0} 60%{transform:scale(1.15);opacity:1} 100%{transform:scale(1)} }
        button { cursor:pointer; font-family:'Space Grotesk',sans-serif; }
        button:focus-visible { outline:2px solid #f2b34c; outline-offset:2px; }
      `}),t==="home"&&(0,r.jsx)(Fy,{go:e,memLvl:n,theme:l,toggleTheme:async()=>{let _=l==="dark"?"light":"dark";i(_);try{await window.storage.set("uke:theme",_)}catch{}}}),t==="tuner"&&(0,r.jsx)(ov,{onBack:()=>e("home")}),t==="strums"&&(0,r.jsx)(lv,{onBack:()=>e("home"),activePat:m,setActivePat:S}),t==="recs"&&(0,r.jsx)(Py,{onBack:()=>e("home")}),t==="karaoke"&&(0,r.jsx)(Qy,{onBack:()=>e("home")}),t==="mp3solo"&&(0,r.jsx)(Xy,{onBack:()=>e("home"),onDone:_=>{A(_),u(_.id),e("library")}}),t==="voix"&&(0,r.jsx)(ev,{onBack:()=>e("home"),onDone:_=>{A(_),u(_.id),e("library")}}),t==="transfer"&&(0,r.jsx)($y,{onBack:()=>e("home")}),t==="patreon"&&(0,r.jsx)(Iy,{onBack:()=>e("home"),onDone:_=>{A(_),u(_.id),e("library")}}),t==="photo"&&(0,r.jsx)(nv,{onBack:()=>e("home"),onDone:_=>{A(_),u(_.id),e("library")}}),t==="ask"&&(0,r.jsx)(iv,{prefill:b,onBack:()=>{x(""),e("home")},onDone:_=>{A(_),u(_.id),e("library")}}),t==="editor"&&(0,r.jsx)(rv,{onBack:()=>{v(null),e(p?"library":"home")},initial:p,save:_=>{p?w(p.id,_):A(_),u(p?p.id:_.id),v(null),e("library")}}),t==="library"&&(0,r.jsx)(Yy,{favs:R,toggleFav:T,lastId:c,onHome:()=>e("home"),extraSongs:o,imports:f,addImport:A,removeImport:X,updateImport:w,onEditTrack:_=>{v(_),e("editor")},onAsk:_=>{x(_),e("ask")},onPlay:(_,B,Q,K)=>{u(_.id),y({song:_,mode:B,diff:Q,level:K}),e("play")}}),t==="play"&&(0,r.jsx)(Vy,{...z,updateImport:w,memLvl:n,onMemUp:async()=>{let _=n+1;a(_);try{await window.storage.set("uke:memlvl",String(_))}catch{}},activePat:m,onBack:()=>e("library"),onSwitch:(_,B)=>y(Q=>({...Q,mode:_,diff:B}))},z.song.id+z.mode+z.diff+(z.level||""))]})}
function Nf({children:t,big:e}){return(0,r.jsx)("div",{style:{position:"fixed",inset:0,background:"var(--ovl)",zIndex:15,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:20,textAlign:"center",...e?{background:"transparent",position:"absolute",pointerEvents:"none"}:{}},children:e?(0,r.jsx)("div",{style:{fontFamily:"'Fraunces',serif",fontSize:64,color:"#f2b34c",textShadow:"0 0 40px rgba(242,179,76,.4)",animation:"pulse .6s infinite"},children:t}):t})}
(0,Rp.createRoot)(document.getElementById("root")).render(Dp.default.createElement(Hf));
